version: '3.8'

services:
  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - DB_HOST=db
      - DB_USER=sepo
      - DB_PASS=sepo123
      - DB_NAME=cms-db
      - JWT_SECRET=super_secret_secret
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql_db
    image: mysql:8
    environment:
      - MYSQL_DATABASE=cms-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sepo
      - MYSQL_PASSWORD=sepo123
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
